buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Старая, лёгкая версия Android Gradle Plugin — достаточно для API 14-30
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
